auth_register: { path: /auth/register, controller: App\Controller\AuthController::register, methods: [POST] }
auth_login:    { path: /auth/login,    controller: App\Controller\AuthController::login,    methods: [POST] }
auth_logout:   { path: /auth/logout,   controller: App\Controller\AuthController::logout,   methods: [POST] }
auth_me:       { path: /auth/me,       controller: App\Controller\AuthController::me,       methods: [GET] }

password_request: { path: /auth/forgot-password, controller: App\Controller\PasswordResetController::request, methods: [POST] }
password_reset:   { path: /auth/reset-password,  controller: App\Controller\PasswordResetController::reset,   methods: [POST] }

contact_create: { path: /api/contact, controller: App\Controller\ContactController::create, methods: [POST] }
contact_can:    { path: /api/contact/can-send, controller: App\Controller\ContactController::canSend, methods: [GET] }
