framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  session: true
  validation: { enable_attributes: true }
  csrf_protection: false

  rate_limiter:
    contact_per_user:
      policy: fixed_window
      limit: 1
      interval: '60 minutes'
