nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:5173']
    allow_headers: ['Content-Type', 'X-Requested-With']
    allow_methods: ['GET','POST','OPTIONS']
    max_age: 3600
  paths:
    '^/': ~
