security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/(auth|api)
      stateless: false
      lazy: true
      provider: app_user_provider
      json_login:
        check_path: /auth/login
        username_path: email
        password_path: password
      logout:
        path: /auth/logout
        invalidate_session: true

  access_control:
    - { path: ^/auth/(login|register|forgot-password|reset-password), roles: PUBLIC_ACCESS }
    - { path: ^/api/contact, roles: ROLE_USER }
    - { path: ^/api, roles: PUBLIC_ACCESS }
